"""Content for the goal-based service pages added after the original seven (dev helper, not deployed).
Each entry uses the same fields as pages_services.SERVICES, plus its WHAT_WHY text.
General information only: no promised returns; legal/tax topics point to professionals."""

LEGAL_NOTE = ('This page is general information, not legal or tax advice. Wills, trusts and succession '
              'arrangements should be prepared with a qualified lawyer; we work alongside your lawyer and chartered accountant.')

EXTRA = [
  dict(
    slug='term-insurance', name='Term Insurance', icon='user-shield', short='Maximum life cover at the lowest premium.',
    what_title='What is term insurance?',
    title='Term Insurance', lead='The simplest, most affordable way to give your family a large financial safety net.',
    desc='Term insurance in Kochi: high life cover at a low premium to protect your family\'s income, loans and goals, with help choosing the right cover and claim support.',
    intro=['We help you work out how much cover your family really needs, compare term plans from leading insurers on price, claim record and features, and make sure every detail in your proposal is correct so a future claim is not disputed.',
           'After the policy is issued, we stay with you: nomination updates, cover reviews as your income and loans change, and full support for your family if a claim is ever made.'],
    benefits=[('user-shield', 'Large cover, low premium', 'A term plan pays only on death, so the premium for a high sum assured is far lower than for savings-linked plans.'),
              ('house-user', 'Loans covered', 'Size the cover so your family can clear a home or car loan and keep the house.'),
              ('calendar-check', 'Fixed premium', 'The premium is usually fixed when you buy, so starting younger costs less for the whole term.'),
              ('file-signature', 'Optional riders', 'Add accidental death, critical illness or waiver-of-premium cover for a small extra cost.'),
              ('percent', 'Tax benefit', 'Premiums may qualify under Section 80C (old tax regime), subject to the rules.'),
              ('handshake', 'Claim support', 'We help your family with the documents and follow up with the insurer until the claim is settled.')],
    audience=['Anyone whose family depends on their income', 'Young parents', 'Home loan borrowers', 'Self-employed people without employer cover', 'People who want high cover on a modest budget'],
    steps=[('Work out your cover', 'We estimate the cover you need from your income, loans and goals.'),
           ('Compare term plans', 'Premiums, claim settlement records, riders and policy terms side by side.'),
           ('Apply correctly', 'We help with the proposal, medicals and full disclosure so a claim is never in doubt.'),
           ('Review and support', 'Regular cover reviews, nomination updates and claim support for your family.')],
    faqs=[('How much term cover do I need?', '<p>A common starting point is 10 to 15 times your annual income, plus your loans. Our <a href="life-cover-calculator.html">life cover calculator</a> gives a more precise figure based on your situation.</p>'),
          ('Do I get anything back if I survive the term?', '<p>A pure term plan pays nothing on survival, which is why it is so affordable. Return-of-premium variants exist but cost much more; we will show you both.</p>'),
          ('Why must I disclose my health and habits?', '<p>Insurers can reject a claim if important facts such as smoking or existing illnesses were not disclosed. Honest, complete disclosure protects your family.</p>')],
    why=dict(
        what=['Term insurance is pure life cover for a fixed period, say 20 or 30 years. If you die during that period, the insurer pays your family the sum assured. If you survive, the policy ends and nothing is paid back.',
              'Because it carries no savings element, it gives the highest cover for the lowest premium.'],
        why='Most families are under-insured: their life cover is far smaller than the income, loans and goals it needs to replace. A term plan closes that gap affordably, so your family is not left with debts and no income.',
        risks=['Your family losing your income overnight', 'Loans passing to your family', "Children's education plans stopping", 'Savings used up to meet daily expenses'])),

  dict(
    slug='general-insurance', name='General Insurance', icon='umbrella', short='Cover for your vehicle, home, travel and more.',
    what_title='What is general insurance?',
    title='General Insurance', lead='Protect your vehicle, home, travel and personal accidents, with help when you need to claim.',
    desc='General insurance in Kochi: motor, home, travel, personal accident and shop insurance from leading insurers, with renewal reminders and claim support.',
    intro=['We compare policies from leading general insurers, including United India, National Insurance, ICICI Lombard and Star Health, and explain exactly what each one covers and excludes.',
           'We remind you before renewals so your cover never lapses, and when something goes wrong we guide you through the claim and follow up with the insurer and surveyor.'],
    benefits=[('car', 'Motor insurance', 'Third-party cover is compulsory by law; comprehensive cover also protects your own vehicle.'),
              ('house-chimney', 'Home insurance', 'Your house and its contents against fire, flood, theft and other perils.'),
              ('plane', 'Travel insurance', 'Medical emergencies, trip cancellation and lost baggage when you travel.'),
              ('person-falling-burst', 'Personal accident', 'A payout for accidental death or disability, alongside your life and health cover.'),
              ('store', 'Shop and office', 'Cover for small premises, stock and equipment.'),
              ('rotate', 'Renewal reminders', 'We track renewal dates so your cover never lapses by mistake.')],
    audience=['Vehicle owners', 'Home owners and tenants', 'Frequent travellers and students going abroad', 'Shop owners and small offices', 'Anyone who wants all their policies looked after in one place'],
    steps=[('Understand what you own', 'Vehicles, property, travel plans and the risks you want to cover.'),
           ('Compare insurers', 'Cover, exclusions, deductibles and price from several insurers.'),
           ('Buy the right policy', 'We help with the proposal, inspections and documents.'),
           ('Renewals and claims', 'Timely renewal reminders and hands-on help with every claim.')],
    faqs=[('Is motor insurance compulsory?', '<p>Third-party motor insurance is compulsory in India. Comprehensive cover, which also pays for damage to your own vehicle, is optional but strongly recommended.</p>'),
          ('Does home insurance cover tenants?', '<p>Yes. Tenants can insure their belongings even if they do not own the building.</p>'),
          ('What should I do first after an accident or loss?', '<p>Inform the insurer quickly, keep photos and bills, and file a police report where required. Call us and we will guide you through each step.</p>')],
    why=dict(
        what=['General insurance covers everything other than life insurance: your vehicle, home, travel, personal accidents and small business premises. Most policies run for one year and are renewed annually.',
              'Each policy pays for a specific loss, such as damage, theft or medical costs abroad, up to the sum insured.'],
        why='Accidents, theft, fire and floods are sudden and expensive. Without cover, the repair or replacement cost comes straight out of your savings, and some covers, such as third-party motor insurance, are required by law.',
        risks=['Expensive repairs after an accident', 'Legal liability to third parties', 'Loss of your home or belongings to fire, flood or theft', 'Medical bills abroad with no cover'])),

  dict(
    slug='sip-investment', name='SIP Investment', icon='calendar-check', short='Invest a fixed amount every month and build wealth steadily.',
    what_title='What is a SIP?',
    title='SIP Investment', lead='Invest a fixed amount every month and let time and discipline do the work.',
    desc='SIP investment in Kochi through an AMFI-registered distributor: start a monthly mutual fund SIP matched to your goals, with KYC help and regular reviews.',
    intro=['As an AMFI-registered Mutual Fund Distributor, we help you choose schemes that match each goal, complete your KYC, set up the SIP mandate with your bank, and review your portfolio with you regularly.',
           'We also show you how a step-up SIP, increasing your instalment each year, can help you reach a goal sooner.'],
    benefits=[('calendar-check', 'Discipline', 'A fixed amount leaves your bank account automatically every month.'),
              ('chart-line', 'Rupee-cost averaging', 'You buy more units when prices are low and fewer when they are high.'),
              ('coins', 'Start small', 'Many SIPs can start from a few hundred rupees a month.'),
              ('arrow-trend-up', 'Step up over time', 'Increase your SIP as your income grows.'),
              ('bullseye', 'Goal-linked', 'Set up a separate SIP for each goal, such as education or retirement.'),
              ('rotate', 'Flexible', 'Pause, increase or stop most SIPs when your needs change.')],
    audience=['First-time investors', 'Salaried people investing from each month\'s pay', 'Parents saving for education', 'Anyone planning for retirement', 'Investors who prefer not to time the market'],
    steps=[('Goals and risk profile', 'What you are investing for, when you need the money and how much volatility you can accept.'),
           ('Compare schemes', 'Suitable schemes explained, with their risk level, costs and track record.'),
           ('Set up the SIP', 'KYC, scheme selection and the bank mandate, done together.'),
           ('Review regularly', 'Periodic reviews and step-ups to keep each SIP on track.')],
    faqs=[('How much should I invest each month?', '<p>Work backwards from the goal: the amount you need and when. Our <a href="sip-calculator.html">SIP calculator</a> and <a href="step-up-sip-calculator.html">step-up SIP calculator</a> help you find the figure.</p>'),
          ('What happens if I miss an instalment?', '<p>Usually nothing serious: the instalment is skipped, though your bank may charge a fee. Several missed instalments can cancel the SIP.</p>'),
          ('Are SIP returns guaranteed?', '<p>No. A SIP is a way of investing in mutual funds, and returns depend on the market.</p>')],
    risk=True,
    why=dict(
        what=['A Systematic Investment Plan (SIP) is a way of investing a fixed amount in a mutual fund at regular intervals, usually every month, by automatic debit from your bank account.',
              'Each instalment buys units at that day\'s price, so over time you build up a holding without needing a large lump sum.'],
        why='Saving whatever is left at the end of the month rarely works, and money in a savings account loses value to inflation. A SIP makes investing automatic and spreads your purchases over time, so you do not have to guess the right moment to invest.',
        risks=['Savings that do not keep pace with inflation', 'Waiting for the "right time" and never starting', 'Investing irregularly and missing goals', 'Stopping in a falling market at the worst moment'])),

  dict(
    slug='wealth-creation', name='Wealth Creation', icon='sack-dollar', short='A long-term plan to grow and preserve your wealth.',
    what_title='What is wealth creation?',
    title='Wealth Creation', lead='Build a strong, resilient financial foundation through strategic planning, smart investments and continuous growth.',
    desc='Wealth creation in Kochi: long-term, goal-based portfolios across mutual funds and insurance, with diversification, regular reviews and a clear roadmap.',
    intro=['True wealth goes beyond accumulation: it is about creating enduring value that supports your ambitions and secures your future. Our Wealth Creation solutions focus on building a strong and resilient financial foundation through strategic planning, smart investments and continuous growth.',
           'By aligning your financial goals with a clear roadmap, we help you unlock opportunities, make the most of your investments and build prosperity that lasts for generations.'],
    benefits=[('route', 'A clear roadmap', 'Every investment is linked to a goal and a time frame.'),
              ('layer-group', 'Diversification', 'A balanced mix across equity, debt and insurance, so no single risk dominates.'),
              ('arrow-trend-up', 'Compounding', 'Staying invested for the long term lets returns build on returns.'),
              ('shield-heart', 'Protection first', 'Adequate life and health cover so a setback does not undo your progress.'),
              ('rotate', 'Regular reviews', 'Rebalancing as markets move and your life changes.'),
              ('file-signature', 'Nominations in order', 'Every holding with an up-to-date nominee, so your wealth reaches the right people.')],
    audience=['Professionals and business owners with growing incomes', 'Families with savings sitting idle', 'Investors with scattered, unreviewed investments', 'Anyone planning for financial independence'],
    steps=[('Understand your goals', 'Where you are today and what you want your wealth to do.'),
           ('Compare options', 'The mix of mutual funds and insurance that suits your goals and risk.'),
           ('Build the portfolio', 'Lump sum, SIPs or a staggered approach, set up step by step.'),
           ('Review and rebalance', 'Regular reviews to keep the plan on track as life changes.')],
    faqs=[('How is wealth creation different from saving?', '<p>Saving keeps money safe; wealth creation puts it to work over long periods through diversified investments, accepting some short-term ups and downs for long-term growth.</p>'),
          ('How long does it take?', '<p>Wealth creation is a long-term process, usually measured in decades rather than years. Starting early matters more than starting big.</p>'),
          ('Do I need a large amount to begin?', '<p>No. Many people begin with a monthly <a href="sip-investment.html">SIP</a> and add lump sums over time.</p>')],
    risk=True,
    why=dict(
        what=['Wealth creation is the long-term process of growing your money beyond what you need today, through a planned, diversified mix of investments, and protecting it so it lasts.',
              'It is built on clear goals, steady investing, sensible diversification and regular reviews.'],
        why='Income alone rarely builds lasting wealth. Without a plan, savings sit idle, investments are scattered, and inflation quietly reduces what your money can buy.',
        risks=['Idle savings losing value to inflation', 'Scattered investments with no overall plan', 'Too much risk in one place', 'One setback wiping out years of progress'])),

  dict(
    slug='marriage-planning', name='Marriage Planning', icon='ring', short='Plan the cost of a wedding without loans or stress.',
    what_title='What is marriage planning?',
    title='Marriage Planning', lead='Celebrate your child\'s wedding, or your own, without loans, stress or dipping into retirement savings.',
    desc='Marriage planning in Kochi: estimate the future cost of a wedding, save steadily through SIPs and insurance, and protect the goal for your family.',
    intro=['We help you put a realistic figure on the wedding you have in mind, allowing for rising costs, and build a savings plan that reaches it on time.',
           'We protect the goal with the right life cover, and as the date approaches we move your savings to safer options so the money is there when you need it.'],
    benefits=[('calculator', 'A realistic budget', "Today's costs projected forward, so the target is clear."),
              ('calendar-check', 'Steady saving', 'Monthly SIPs sized to the years you have.'),
              ('user-shield', 'Goal protection', 'Life cover so the plan continues even if a parent is not there.'),
              ('shield-heart', 'Retirement kept safe', 'A separate fund, so you do not have to break your retirement savings.'),
              ('route', 'Safer as the date nears', 'Money moved to lower-risk options in the final years.'),
              ('gem', 'Gold and jewellery', 'A plan for jewellery purchases, staggered over time.')],
    audience=['Parents of children who will marry in 5 to 20 years', 'Young couples planning their own wedding', 'Families who want to avoid wedding loans', 'Parents who want to protect their retirement savings'],
    steps=[('Set the goal', 'The kind of wedding, the likely year and today\'s estimated cost.'),
           ('Compare options', 'SIPs, deposits and insurance, matched to the time frame.'),
           ('Plan and protect', 'A monthly saving plan with life cover for the goal.'),
           ('Review each year', 'Adjust as costs and plans change, and de-risk as the date nears.')],
    faqs=[('How far in advance should we start?', '<p>As early as possible. With 10 to 15 years, a modest monthly SIP can build a substantial fund; with 2 to 3 years, safer options and a larger monthly amount are needed.</p>'),
          ('How do we estimate the future cost?', '<p>Start with today\'s cost and allow for rising prices. Our <a href="inflation-calculator.html">inflation calculator</a> and <a href="sip-calculator.html">SIP calculator</a> help you size the plan.</p>'),
          ('Should we use a personal loan?', '<p>Loans add interest costs and pressure after the wedding. Planning ahead usually means you can avoid them.</p>')],
    risk=True,
    why=dict(
        what=['Marriage planning means estimating what a wedding will cost when the time comes, and building a dedicated fund to pay for it, through regular saving and suitable investments.',
              'It works like any other goal: a target amount, a date and a monthly plan to get there.'],
        why='Weddings are among the largest expenses an Indian family faces, and costs rise every year. Without a plan, families often take loans or dip into retirement savings to pay for them.',
        risks=['High-interest loans for the wedding', 'Retirement savings used up early', 'Costs rising faster than expected', 'The plan stopping if a parent is no longer there'])),

  dict(
    slug='goal-based-planning', name='Goal-Based Planning', icon='bullseye', short='Turn every life goal into a clear, funded plan.',
    what_title='What is goal-based planning?',
    title='Goal-Based Planning', lead='Turn each of your life goals into a clear number, a date and a plan to get there.',
    desc='Goal-based financial planning in Kochi: list your goals, put a cost and date on each, and get a single plan of savings, investments and protection.',
    intro=['In a free consultation we list your goals together: a home, children\'s education and weddings, retirement, travel or a business. We put a cost and a date on each, and check what you already have.',
           'Then we build one joined-up plan: how much to save for each goal, where to invest it, and the protection needed so a setback does not derail it. We review it with you every year.'],
    benefits=[('list-check', 'Clear priorities', 'Every goal listed, costed and ranked.'),
              ('bullseye', 'Separate buckets', 'Money for each goal kept and invested separately.'),
              ('calculator', 'Real numbers', 'Future costs that allow for inflation.'),
              ('layer-group', 'The right risk', 'Short-term goals in safer options, long-term goals in growth assets.'),
              ('shield-heart', 'Protected plan', 'Life and health cover so one event does not undo the plan.'),
              ('rotate', 'Annual review', 'Progress tracked and the plan updated each year.')],
    audience=['Young professionals starting out', 'Families juggling several goals at once', 'Anyone unsure whether they are saving enough', 'People with investments but no overall plan'],
    steps=[('List your goals', 'Each goal, its cost today and when you need the money.'),
           ('Compare and prioritise', 'What you have, what you need and the gap for each goal.'),
           ('Build the plan', 'Savings, investments and protection matched to each goal.'),
           ('Review every year', 'Track progress and adjust as life changes.')],
    faqs=[('What goals can be planned for?', '<p>Any goal with a cost and a date: buying a home, education, weddings, a vehicle, travel, starting a business or retirement.</p>'),
          ('What if I cannot afford every goal?', '<p>We help you prioritise, adjust timelines or targets, and focus first on the essentials such as protection and retirement.</p>'),
          ('How do I start?', '<p>Book a <a href="financial-checkup.html">free financial checkup</a>. Bring a rough idea of your goals and current savings; we will do the rest.</p>')],
    risk=True,
    why=dict(
        what=['Goal-based planning starts with what you want to achieve, not with products. Each goal gets a target amount, a date and its own savings and investment plan.',
              'It brings your insurance, savings and investments together into one plan that you can track.'],
        why='Without clear goals, money tends to be saved randomly and spent on whatever comes up. Linking every rupee to a purpose makes it far more likely that you reach the goals that matter most.',
        risks=['Saving without knowing if it is enough', 'One goal crowding out another', 'Investments that do not match the time frame', 'Important goals left unfunded'])),

  dict(
    slug='estate-planning', name='Estate Planning', icon='scroll', short='Make sure your wealth reaches the right people, smoothly.',
    what_title='What is estate planning?',
    title='Estate Planning', lead='Make sure everything you have built reaches the right people, smoothly and without disputes.',
    desc='Estate planning support in Kochi: nominations, wills, record keeping and insurance, so your family receives your assets smoothly. We work alongside your lawyer.',
    intro=['We start by listing everything you own: insurance policies, mutual funds, deposits, property and other assets, and checking that each has the right nominee and ownership.',
           'We help you organise clear records for your family, use life insurance to provide ready money, and work alongside your lawyer when you make or update your will.'],
    benefits=[('file-signature', 'Correct nominations', 'Every policy and investment with an up-to-date nominee.'),
              ('scroll', 'A clear will', 'Pointers on making a will with a lawyer, so your wishes are followed.'),
              ('folder-open', 'Organised records', 'One place where your family can find every asset and contact.'),
              ('hand-holding-dollar', 'Ready money', 'Life insurance that gives your family cash while other assets are transferred.'),
              ('people-group', 'Fewer disputes', 'Clear instructions reduce the chance of family disagreements.'),
              ('rotate', 'Regular updates', 'Reviews after marriage, a birth, a death or a major purchase.')],
    audience=['Anyone with a family who depends on them', 'Parents of young children', 'People with property or several investments', 'Retirees', 'NRIs with assets in India'],
    steps=[('List your assets', 'Insurance, investments, deposits, property and liabilities.'),
           ('Check and compare', 'Nominations, ownership and gaps against your wishes.'),
           ('Put the plan in place', 'Update nominations, organise records and work with your lawyer on the will.'),
           ('Keep it current', 'Review after every major life event.')],
    faqs=[('Is a nomination the same as a will?', '<p>No. In many cases a nominee receives the money on behalf of the legal heirs rather than as the final owner. Your nominations and your will should agree; a lawyer can advise on your situation.</p>'),
          ('Do I need a will if I am young?', '<p>If anyone depends on you, or you own any assets, a simple will makes things far easier for your family.</p>'),
          ('Do you draft wills?', '<p>No. We help you organise your assets and nominations and work alongside a qualified lawyer, who prepares the will.</p>')],
    legal=True,
    why=dict(
        what=['Estate planning means deciding who should receive your assets after you, and making sure the paperwork, nominations, will and records, makes that happen smoothly.',
              'It also covers providing your family with ready money and clear information at a difficult time.'],
        why='Without a plan, families can face months of paperwork, frozen accounts and sometimes disputes, just when they need support. Simple steps taken today can save your family a great deal of stress.',
        risks=['Assets stuck without a nominee or will', 'Disputes between family members', 'Your family unaware of what you own', 'No ready money while assets are transferred'])),

  dict(
    slug='succession-planning', name='Succession Planning', icon='sitemap', short='Plan who takes over your business and family assets.',
    what_title='What is succession planning?',
    title='Succession Planning', lead='Plan for the continuity of your business and family assets, so the next generation can carry on.',
    desc='Succession planning in Kochi for business owners and families: key-person and partnership insurance, nominations and continuity planning, alongside your lawyer and CA.',
    intro=['For business owners, we look at who would run or own the business if something happened to you, and use key-person and partnership insurance to provide the money that makes a smooth handover possible.',
           'For families, we make sure ownership, nominations and insurance support your wishes, and work alongside your lawyer and chartered accountant on the legal and tax side.'],
    benefits=[('user-shield', 'Key-person insurance', 'Money for the business if a founder or key person dies.'),
              ('handshake', 'Partnership protection', 'Funds for surviving partners to buy out a deceased partner\'s share.'),
              ('sitemap', 'A clear handover', 'Who takes over, and when, agreed in advance.'),
              ('people-group', 'Family harmony', 'Clear arrangements reduce the risk of disputes.'),
              ('file-signature', 'Nominations aligned', 'Policies and investments that match your succession plan.'),
              ('rotate', 'Reviewed regularly', 'Updated as the business and family change.')],
    audience=['Business owners and partners', 'Family businesses', 'Professionals with their own practice', 'Families with property and several heirs'],
    steps=[('Understand the situation', 'Your business, family, assets and wishes.'),
           ('Compare options', 'Key-person, partnership and life cover, and how each would work.'),
           ('Put protection in place', 'The right policies and nominations, alongside your lawyer and CA.'),
           ('Review regularly', 'Keep the plan aligned as the business grows.')],
    faqs=[('What is key-person insurance?', '<p>A life policy taken by a business on a person it depends on. If that person dies, the payout helps the business cover lost income, repay loans or find a replacement.</p>'),
          ('How does insurance help partners?', '<p>Each partner can be insured so that, if one dies, the others receive money to buy that partner\'s share from the family, keeping the business running and the family paid fairly.</p>'),
          ('Do I need a lawyer?', '<p>Yes, for agreements, wills and any trust. We work alongside your lawyer and chartered accountant on the insurance and investment side.</p>')],
    legal=True,
    why=dict(
        what=['Succession planning decides who will own and run your business or manage family assets when you step back or if something happens to you, and puts the money and paperwork in place to make that possible.',
              'For businesses it often uses key-person and partnership insurance; for families it aligns ownership, nominations and wills.'],
        why='Many businesses struggle or close when the owner dies or falls ill unexpectedly, and families can disagree over who gets what. Planning ahead protects both the business and the relationships.',
        risks=['The business stalling without its key person', 'Partners unable to buy out a share', 'Disputes between heirs', 'Assets sold in a hurry at a poor price'])),

  dict(
    slug='wealth-transfer', name='Wealth Transfer', icon='people-arrows', short='Pass your wealth to the next generation, efficiently.',
    what_title='What is wealth transfer?',
    title='Wealth Transfer', lead='Pass on what you have built to the next generation, during your lifetime and after, smoothly and efficiently.',
    desc='Wealth transfer planning in Kochi: use insurance, nominations, joint holdings and investments for children to pass wealth to the next generation smoothly.',
    intro=['We help you decide what you would like to pass on, to whom and when, and choose the right tools: life insurance payouts, investments in your children\'s or grandchildren\'s names, nominations and joint holdings.',
           'We explain the tax points to discuss with your chartered accountant, and work alongside your lawyer where a will or trust is needed.'],
    benefits=[('hand-holding-dollar', 'Insurance as a transfer tool', 'A life policy creates a defined sum for your heirs.'),
              ('gift', 'Lifetime gifts', 'Helping children and grandchildren while you can see the benefit.'),
              ('people-arrows', 'Smooth handover', 'Nominations and ownership arranged so money reaches heirs quickly.'),
              ('graduation-cap', 'Investments for the next generation', 'SIPs and plans for children\'s and grandchildren\'s goals.'),
              ('scale-balanced', 'Fair between heirs', 'A plan that treats everyone as you intend.'),
              ('file-signature', 'Paperwork in order', 'Records and nominations that match your wishes.')],
    audience=['Parents and grandparents', 'Retirees with surplus savings', 'Business owners planning for the next generation', 'NRIs with family in India'],
    steps=[('Understand your wishes', 'What you want to pass on, to whom and when.'),
           ('Compare the options', 'Insurance, gifts, investments and nominations, and how each works.'),
           ('Put it in place', 'Policies, investments and paperwork, with your lawyer and CA where needed.'),
           ('Review over time', 'Update as your family and wealth change.')],
    faqs=[('Is a gift to my child taxed?', '<p>Gifts from specified relatives such as parents are generally not taxed in the hands of the recipient. However, income earned on money gifted to a minor child is usually added to the parent\'s income. Please confirm your situation with a chartered accountant.</p>'),
          ('How does life insurance help with wealth transfer?', '<p>The payout goes to your nominee quickly and creates a known sum for your heirs, without needing to sell other assets.</p>'),
          ('Should I transfer assets now or later?', '<p>It depends on your needs, your heirs and the assets involved. We help you weigh the options, keeping enough for your own retirement first.</p>')],
    legal=True,
    why=dict(
        what=['Wealth transfer is how your money and assets pass to the next generation, through gifts during your lifetime, investments in their names, life insurance payouts, nominations and your will.',
              'Planning it means your family receives what you intend, at the right time, with as little cost and delay as possible.'],
        why='Without a plan, wealth can be delayed, reduced by avoidable costs, or divided in ways you did not intend. A little planning makes sure your hard work benefits the people you care about.',
        risks=['Wealth reaching heirs slowly or not as intended', 'Avoidable costs and paperwork', 'Unequal treatment of children by accident', 'Your own retirement left short by giving too early'])),
]

# Sidebar / navigation grouping: goal id -> (title, [slugs])
GOAL_SERVICES = {
    'protect-family': ('Protect Your Family', ['life-insurance', 'term-insurance', 'health-insurance', 'general-insurance', 'corporate-insurance']),
    'grow-wealth': ('Grow Your Wealth', ['mutual-funds', 'sip-investment', 'wealth-creation', 'tax-planning']),
    'plan-future': ('Plan Your Future', ['retirement-planning', 'child-education', 'marriage-planning', 'goal-based-planning']),
    'protect-legacy': ('Protect Your Legacy', ['estate-planning', 'succession-planning', 'wealth-transfer']),
}
